#if SwiftUUIDV7Foundation
  #if canImport(FoundationEssentials)
    import FoundationEssentials
  #elseif canImport(Foundation)
    import Foundation
  #endif
#endif

#if SwiftUUIDV7Foundation && (canImport(FoundationEssentials) || canImport(Foundation))
  // MARK: - Constants

  extension UUID {
    /// A nil UUID defined by RFC 9562.
    @_disfavoredOverload
    @available(*, deprecated, renamed: "min")
    public static let `nil` = Self.min

    /// The min UUID, also known as the nil UUID defined by RFC 9562, where all bits are zero.
    @_disfavoredOverload
    public static let min = Self(uuid: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))

    /// A max UUID defined by RFC 9562.
    @_disfavoredOverload
    public static let max = Self(
      uuid: (
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
      )
    )
  }

  // MARK: - Version

  extension UUID {
    /// The version number of this UUID as defined by RFC 9562.
    @_disfavoredOverload
    public var version: Int {
      get { Int(self.uuid.6 >> 4) }
      set {
        var bytes = self.uuid
        bytes.6 = (bytes.6 & 0x0F) | (UInt8(newValue & 0x0F) << 4)
        self = UUID(uuid: bytes)
      }
    }
  }

  // MARK: - Variant

  extension UUID {
    /// The variant of this UUID as defined by RFC 9562.
    @_disfavoredOverload
    @available(*, deprecated, message: "Use UUIDVariant(uuid:) instead.")
    public var variant: UUIDVariant {
      UUIDVariant(uuid: self.uuid)
    }
  }

  // MARK: - Random

  extension UUID {
    /// Generates a new random UUID.
    ///
    /// - Parameter generator: The random number generator to use when creating the new random
    ///   value.
    /// - Returns: A random UUID.
    @_disfavoredOverload
    public static func random(using generator: inout some RandomNumberGenerator) -> UUID {
      var bytes = UUIDV7.randomBytes(using: &generator)
      bytes.6 = (bytes.6 & 0x0F) | 0x40
      bytes.8 = (bytes.8 & 0x3F) | 0x80
      return UUID(uuid: bytes)
    }

    /// Creates a new UUID with RFC 9562 version 4 (random) layout. This is equivalent to calling
    /// `UUID()`.
    @_disfavoredOverload
    public static func version4() -> UUID {
      UUID()
    }
  }

  // MARK: - Version 7

  extension UUID {
    /// Creates a new UUID with RFC 9562 version 7 layout.
    ///
    /// UUIDs generated without a `date` are guaranteed to be monotonically increasing within the
    /// current process, including alongside UUIDs generated by ``UUIDV7``.
    ///
    /// - Parameters:
    ///   - date: The date to encode in the timestamp field. If `nil`, the current time is used.
    ///   - offset: A duration to add to the timestamp before encoding.
    @_disfavoredOverload
    public static func version7(at date: Date? = nil, offset: Duration = .zero) -> UUID {
      if let date {
        UUIDV7(timeIntervalSince1970: Self.clampedTimeInterval(date, offset)).rawValue
      } else {
        UUIDV7(_clampingOffset: offset).rawValue
      }
    }

    /// Creates a new UUID with RFC 9562 version 7 layout using the specified random number
    /// generator for the random bits.
    ///
    /// UUIDs generated without a `date` are guaranteed to be monotonically increasing within the
    /// current process, including alongside UUIDs generated by ``UUIDV7``.
    ///
    /// - Parameters:
    ///   - generator: The random number generator to use when creating the random bits.
    ///   - date: The date to encode in the timestamp field. If `nil`, the current time is used.
    ///   - offset: A duration to add to the timestamp before encoding.
    @_disfavoredOverload
    public static func version7(
      using generator: inout some RandomNumberGenerator,
      at date: Date? = nil,
      offset: Duration = .zero
    ) -> UUID {
      if let date {
        UUIDV7(
          timeIntervalSince1970: Self.clampedTimeInterval(date, offset),
          using: &generator
        )
        .rawValue
      } else {
        UUIDV7(_clampingOffset: offset, using: &generator).rawValue
      }
    }

    // NB: Foundation clamps timestamps before 1970 to 0 instead of trapping like UUIDV7, so these
    // backports clamp to match Foundation.

    private static func clampedTimeInterval(_ date: Date, _ offset: Duration) -> TimeInterval {
      Swift.max(0, date.timeIntervalSince1970 + offset.uuidV7TimeInterval)
    }
  }

  // MARK: - Date

  extension UUID {
    /// For version 7 UUIDs, returns the `Date` encoded in the most significant 48 bits. Returns
    /// `nil` for all other versions.
    @_disfavoredOverload
    public var date: Date? {
      guard self.version == 7 else { return nil }
      return Date(timeIntervalSince1970: UUIDV7._timeIntervalSince1970(self.uuid))
    }
  }

  // MARK: - Lowercased UUID String

  extension UUID {
    /// Returns a lowercase string created from the UUID, such as
    /// "e621e1f8-c36c-495a-93fc-0c247a3e6e5f".
    @_disfavoredOverload
    public var lowercasedUUIDString: String {
      UUIDV7._uuidString(self.uuid, lowercased: true)
    }
  }

  // MARK: - Span Initializers

  #if compiler(>=6.2)
    extension UUID {
      /// Creates a UUID by copying exactly 16 bytes from a `RawSpan`.
      ///
      /// - Precondition: `span.byteCount` must be exactly 16.
      @_disfavoredOverload
      public init(copying span: RawSpan) {
        self.init(uuid: UUIDV7._uuidBytes(copying: span))
      }

      /// Creates a UUID by filling its 16 bytes using a closure that writes into an
      /// `OutputRawSpan`.
      ///
      /// - Precondition: `initializer` must write exactly 16 bytes.
      @_disfavoredOverload
      public init<E: Error>(
        initializingWith initializer: (inout OutputRawSpan) throws(E) -> Void
      ) throws(E) {
        try self.init(uuid: UUIDV7._uuidBytes(initializingWith: initializer))
      }
    }
  #endif
#endif
