name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS
    runs-on: macos-15
    strategy:
      matrix:
        xcode: ["16.3"]
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} tests
        run: swift test --configuration ${{ matrix.config }} --enable-all-traits

  linux-android:
    name: Linux + Android
    runs-on: ubuntu-latest
    container: swift:6.1
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Linux"
        run: swift test --configuration ${{ matrix.config }} --traits SwiftUUIDV7Tagged,SwiftUUIDV7StructuredQueries
      - name: "Test Swift Package on Android"
        uses: swift-android-sdk/swift-android-action@v2
        with:
          swift-version: 6.1
          swift-test-flags: --configuration ${{ matrix.config }} --traits SwiftUUIDV7Tagged,SwiftUUIDV7StructuredQueries

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Swift on Windows"
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE
      - name: "Test Swift Package on Windows"
        run: swift test --configuration ${{ matrix.config }} --traits SwiftUUIDV7Tagged

  wasm:
    name: WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Swift and Swift SDK for WebAssembly
        run: |
          PREFIX=/opt/swift
          set -ex
          curl -f -o /tmp/swift.tar.gz "https://download.swift.org/swift-6.1-release/ubuntu2204/swift-6.1-RELEASE/swift-6.1-RELEASE-ubuntu22.04.tar.gz"
          sudo mkdir -p $PREFIX; sudo tar -xzf /tmp/swift.tar.gz -C $PREFIX --strip-component 1
          $PREFIX/usr/bin/swift sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-6.1-RELEASE/swift-wasm-6.1-RELEASE-wasm32-unknown-wasi.artifactbundle.zip --checksum 7550b4c77a55f4b637c376f5d192f297fe185607003a6212ad608276928db992
          echo "$PREFIX/usr/bin" >> $GITHUB_PATH
      - name: Build tests
        run: swift build --traits SwiftUUIDV7Tagged --triple wasm32-unknown-wasi --build-tests
      - name: Run tests
        run: wasmtime .build/debug/swift-uuidv7PackageTests.wasm
