name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: UUIDV7 vs Foundation UUID (Throughput)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app
      - name: Install Dependencies
        run: brew install jemalloc
      - name: Run Benchmark
        run: |
          cd Benchmarks
          swift package benchmark --target swift-uuidv7-benchmarks

  macos:
    name: macOS
    runs-on: macos-15
    strategy:
      matrix:
        xcode: ["16.3"]
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} tests
        run: swift test --configuration ${{ matrix.config }} --enable-all-traits

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Linux"
        run: swift test --configuration ${{ matrix.config }} --traits SwiftUUIDV7Tagged,SwiftUUIDV7StructuredQueries,SwiftUUIDV7Dependencies

  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Android"
        uses: swift-android-sdk/swift-android-action@v2
        with:
          swift-version: 6.1
          swift-build-flags: --traits SwiftUUIDV7Tagged,SwiftUUIDV7StructuredQueries,SwiftUUIDV7Dependencies
          swift-configuration: release

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Swift on Windows"
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE
      - name: "Test Swift Package on Windows"
        run: swift test --configuration ${{ matrix.config }} --traits SwiftUUIDV7Tagged

  wasm:
    name: WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v2
        with:
          tag: swift-6.1-RELEASE
      - name: Build
        run: swift build --build-tests --swift-sdk wasm32-unknown-wasi --traits SwiftUUIDV7Tagged
